### ISSUE TITLE
Using numeric counter in the middle of an identifier

### ISSUE THREAD

**Issue by WiredSound** [dtolnay/seq-macro#18] opened 2022-05-19 19:14 UTC
I'm attempting to simplify the process of dealing with OpenGL uniform functions `gl::Uniform1f`, `gl::Uniform2f`, ...

`seq` gets very close to making this a very easy process - the only issue is that the numeric counter cannot currently be used in the middle of the identifier as far as I can tell. Code in the form `seq!(N in 1..=4 { gl::Uniform~N~f(...); });` unfortunately does not compile with `no rules expected this token in macro call`.

**Comment by dtolnay** [comment] 2022-05-19 19:52
This is a duplicate of #14.

**Closed** 2022-05-19 19:55 UTC
